var multiItemSlider=function(){return function(v,w){var c=document.querySelector(".one"),m=c.querySelector(".slider__wrapper_g"),n=c.querySelectorAll(".slider__item"),t=c.querySelectorAll(".slider__control"),d=c.querySelector(".slider__control_left"),f=c.querySelector(".slider__control_right"),g=parseFloat(getComputedStyle(m).width),h=parseFloat(getComputedStyle(n[0]).width),b=0,k=0,p=h/g*100,q=[];n.forEach(function(a,b){q.push({item:a,position:b,transform:0})});var r=q.length-1,l=function(a){if("right"===
a){if(b+g/h-1>=r)return;d.classList.contains("slider__control_show")||d.classList.add("slider__control_show");f.classList.contains("slider__control_show")&&b+g/h>=r&&f.classList.remove("slider__control_show");b++;k-=p}if("left"===a){if(0>=b)return;f.classList.contains("slider__control_show")||f.classList.add("slider__control_show");d.classList.contains("slider__control_show")&&0>=b-1&&d.classList.remove("slider__control_show");b--;k+=p}m.style.transform="translateX("+k+"%)"},u=function(a){a.target.classList.contains("slider__control")&&
(a.preventDefault(),a=a.target.classList.contains("slider__control_right")?"right":"left",l(a))};(function(){t.forEach(function(a){a.addEventListener("click",u)})})();return{right:function(){l("right")},left:function(){l("left")}}}}(),slider=multiItemSlider(".slider");"use strict";
multiItemSlider=function(){return function(v,w){var c=document.querySelector(".two"),m=c.querySelector(".slider__wrapper_g"),n=c.querySelectorAll(".slider__item"),t=c.querySelectorAll(".slider__control"),d=c.querySelector(".slider__control_left"),f=c.querySelector(".slider__control_right"),g=parseFloat(getComputedStyle(m).width),h=parseFloat(getComputedStyle(n[0]).width),b=0,k=0,p=h/g*100,q=[];n.forEach(function(a,b){q.push({item:a,position:b,transform:0})});var r=q.length-1,l=function(a){if("right"===
a){if(b+g/h-1>=r)return;d.classList.contains("slider__control_show")||d.classList.add("slider__control_show");f.classList.contains("slider__control_show")&&b+g/h>=r&&f.classList.remove("slider__control_show");b++;k-=p}if("left"===a){if(0>=b)return;f.classList.contains("slider__control_show")||f.classList.add("slider__control_show");d.classList.contains("slider__control_show")&&0>=b-1&&d.classList.remove("slider__control_show");b--;k+=p}m.style.transform="translateX("+k+"%)"},u=function(a){a.target.classList.contains("slider__control")&&
(a.preventDefault(),a=a.target.classList.contains("slider__control_right")?"right":"left",l(a))};(function(){t.forEach(function(a){a.addEventListener("click",u)})})();return{right:function(){l("right")},left:function(){l("left")}}}}();slider=multiItemSlider(".slider");"use strict";
multiItemSlider=function(){return function(v,w){var c=document.querySelector(".three"),m=c.querySelector(".slider__wrapper_g"),n=c.querySelectorAll(".slider__item"),t=c.querySelectorAll(".slider__control"),d=c.querySelector(".slider__control_left"),f=c.querySelector(".slider__control_right"),g=parseFloat(getComputedStyle(m).width),h=parseFloat(getComputedStyle(n[0]).width),b=0,k=0,p=h/g*100,q=[];n.forEach(function(a,b){q.push({item:a,position:b,transform:0})});var r=q.length-1,l=function(a){if("right"===
a){if(b+g/h-1>=r)return;d.classList.contains("slider__control_show")||d.classList.add("slider__control_show");f.classList.contains("slider__control_show")&&b+g/h>=r&&f.classList.remove("slider__control_show");b++;k-=p}if("left"===a){if(0>=b)return;f.classList.contains("slider__control_show")||f.classList.add("slider__control_show");d.classList.contains("slider__control_show")&&0>=b-1&&d.classList.remove("slider__control_show");b--;k+=p}m.style.transform="translateX("+k+"%)"},u=function(a){a.target.classList.contains("slider__control")&&
(a.preventDefault(),a=a.target.classList.contains("slider__control_right")?"right":"left",l(a))};(function(){t.forEach(function(a){a.addEventListener("click",u)})})();return{right:function(){l("right")},left:function(){l("left")}}}}();slider=multiItemSlider(".slider");"use strict";
multiItemSlider=function(){return function(v,w){var c=document.querySelector(".four"),m=c.querySelector(".slider__wrapper_g"),n=c.querySelectorAll(".slider__item"),t=c.querySelectorAll(".slider__control"),d=c.querySelector(".slider__control_left"),f=c.querySelector(".slider__control_right"),g=parseFloat(getComputedStyle(m).width),h=parseFloat(getComputedStyle(n[0]).width),b=0,k=0,p=h/g*100,q=[];n.forEach(function(a,b){q.push({item:a,position:b,transform:0})});var r=q.length-1,l=function(a){if("right"===
a){if(b+g/h-1>=r)return;d.classList.contains("slider__control_show")||d.classList.add("slider__control_show");f.classList.contains("slider__control_show")&&b+g/h>=r&&f.classList.remove("slider__control_show");b++;k-=p}if("left"===a){if(0>=b)return;f.classList.contains("slider__control_show")||f.classList.add("slider__control_show");d.classList.contains("slider__control_show")&&0>=b-1&&d.classList.remove("slider__control_show");b--;k+=p}m.style.transform="translateX("+k+"%)"},u=function(a){a.target.classList.contains("slider__control")&&
(a.preventDefault(),a=a.target.classList.contains("slider__control_right")?"right":"left",l(a))};(function(){t.forEach(function(a){a.addEventListener("click",u)})})();return{right:function(){l("right")},left:function(){l("left")}}}}();slider=multiItemSlider(".slider");"use strict";
multiItemSlider=function(){return function(v,w){var c=document.querySelector(".five"),m=c.querySelector(".slider__wrapper_g"),n=c.querySelectorAll(".slider__item"),t=c.querySelectorAll(".slider__control"),d=c.querySelector(".slider__control_left"),f=c.querySelector(".slider__control_right"),g=parseFloat(getComputedStyle(m).width),h=parseFloat(getComputedStyle(n[0]).width),b=0,k=0,p=h/g*100,q=[];n.forEach(function(a,b){q.push({item:a,position:b,transform:0})});var r=q.length-1,l=function(a){if("right"===
a){if(b+g/h-1>=r)return;d.classList.contains("slider__control_show")||d.classList.add("slider__control_show");f.classList.contains("slider__control_show")&&b+g/h>=r&&f.classList.remove("slider__control_show");b++;k-=p}if("left"===a){if(0>=b)return;f.classList.contains("slider__control_show")||f.classList.add("slider__control_show");d.classList.contains("slider__control_show")&&0>=b-1&&d.classList.remove("slider__control_show");b--;k+=p}m.style.transform="translateX("+k+"%)"},u=function(a){a.target.classList.contains("slider__control")&&
(a.preventDefault(),a=a.target.classList.contains("slider__control_right")?"right":"left",l(a))};(function(){t.forEach(function(a){a.addEventListener("click",u)})})();return{right:function(){l("right")},left:function(){l("left")}}}}();slider=multiItemSlider(".slider");
$(function(){$(".gallery-container").children().filter(":odd").hide();$(".gallery-container").children().filter(":even").click(function(){$(this).next().slideDown();$(this).hide()});$(".close").click(function(){$(this).parent().parent().slideToggle();$(this).parent().parent().prev().show()});$(".gallery-block").click(function(){$("html,body").animate({scrollTop:$(".gallery-container").offset().top=200},500);e.preventDefault()})});